### ISSUE TITLE
Date search is not doing what I expect it to

### ISSUE THREAD

**Issue by yemoski** [POLDER-Crew/polder-federated-search#179]
Search for the text "A Reconnaissance Snow Survey". The first result has a collection start date of March 2007.

But if I put 2007-01-01 in the first date field, which means that I want to look at data sets that started collection after January 1st, 2007, that result is filtered out.

**Comment by nein09** [comment]
The original dataset that I noticed this with has its temporal coverage specified as "2007-Mar-19/2007-Apr-26", which is not actually a valid date according to the SoSo guidelines. I'm going to close this as won't fix, but it's not a bad idea to try and deal with this kind of thing in the future.
