### ISSUE TITLE
Update annual / quarterly reports / meetings list

### ISSUE THREAD

**Issue by yemoski** [POLDER-Crew/polder-federated-search#180]
Annual Report: https://docs.google.com/document/d/122DyTc4z16GcGLzuTQBGWpasRkChOek2ZaiEU77KVgw/edit#

Quarterly Report: https://drive.google.com/drive/u/0/folders/1H2IG-u2m1zEMfY6pzJqKYNvh2piuij7C

Meetings list (if you attend a meeting, record it here): https://docs.google.com/spreadsheets/d/1YhFuGVEPdAfk8hDxUdCk8jAw_6wR-oJ2JgrD9ODK08I/edit#gid=0

**Comment by yemoski** [comment]
The parent quarterly reports folder is here: https://drive.google.com/drive/u/1/folders/1lq3SNQat1QcxMq4SYgJWdWz1NkWkCXDm - Connect your Google account

**Comment by nein09** [comment]
I'm going to delete this one because it's mostly a reminder for me, personally. But thanks for including it.
