### ISSUE TITLE
API-based indexing for Gleaner

### ISSUE THREAD

**Issue by yemoski** [POLDER-Crew/polder-federated-search#183]
DataStream has an API that returns JSON-LD, given an API key in the request header.

CCADI has a paged JSON-LD API.

On https://api.datacite.org/graphql, you can do things like
`{
  organization(id: "ror.org/01rhff309") {
    datasets {
      totalCount
      nodes {
        id
        titles {
          title
        }
         relatedIdentifiers {
            relatedIdentifier
            relationType
          }
          fundingReferences {
            awardTitle
            awardNumber
          }
           descriptions {
        description
      }
      creators {
        name
        familyName
      }
        geolocations {
          geolocationBox{
            eastBoundLongitude
            westBoundLongitude
            southBoundLatitude
            northBoundLatitude
          }
          geolocationPlace
          geolocationPoint{
            pointLatitude
            pointLongitude
          }
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}`

and get something that's shaped sort of like what we want.

Given the right changes to gleaner, the things that these APIs return could be loaded directly into the triplestore.

**Comment by yemoski** [comment]
CIOOS uses a CKAN API. It'd be pretty neat to support CKAN, that's a widely adopted technology.

**Comment by yemoski** [comment]
This has been on their radar too, in a similar way! [iodepo/odis-arch: Issue #140](https://github.com/iodepo/odis-arch/issues/140)

**Comment by nein09** [comment]
Just mass-closed issues that are tagged as completed, because that's what you do with completed issues! thanks.
